config/routes.rb
Rails.application.routes.draw do
  get 'guesses/new'

  get 'stories/index'

  get 'stories/new'

  get 'stories/edit'

  get 'users/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "users#index"
  
  resources :users
  
  resources :stories do
    resources :guesses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :story
  belongs_to :user
  belongs_to :author, :class_name => 'User' 
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates :text, presence: true, length: { minimum: 5, maximum: 140}, on: :create
  has_many :guesses
  
  def user_has_guessed? u
    guesses.where(user: u).exists?
  end
  
  def get_guess_for_user u
    guesses.where(user: u).take
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :stories
  has_many :guesses
         
  def number_of_stories
    stories.count
  end
  
  def number_of_guesses
    guesses.count
  end
  
  def interest_in_stories
    stories.joins(:guesses).count
  end
  
  def correct_guesses
    count = 0
    guesses.each do |g|
      count += 1 if g.author == g.story.user
    end
    count
  end
  
  def points
    (number_of_stories * 2) + number_of_guesses + interest_in_stories + (correct_guesses * 10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  
  def new
  end
  
  def create
    story = Story.find(params[:story_id])
    author = User.find(params[:guess][:author_id])
    story.guesses.create(user: current_user, author: author)
    redirect_to stories_path
  end
 
  private
    def guess_params
      params.require(:guess).permit(:author_id)
    end
  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  def index
    @current_user_stories = Story.where(user: current_user)
    @other_user_stories = Story.where.not(user: current_user).shuffle
    @guessed_stories = Story.joins(:guesses).where(guesses: {user: current_user})
  end
  
  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
    @scount = Story.where(user: current_user).count
    @gcount = Guess.where(user: current_user).count
  end
  
  def edit
    @story = Story.find(params[:id])
  end
 
  def create
    @story = Story.new(story_params)
    @scount = Story.where(user: current_user).count
    @gcount = Guess.where(user: current_user).count

    @story.user = current_user
    
    if @story.save
      redirect_to stories_path
    else
      render 'new'
    end
  end
  
  def update
    @story = Story.find(params[:id])
 
    if @story.update(story_params)
      redirect_to stories_path
    else
      render 'edit'
    end
  end
 
  private 
  def story_params
    params.require(:story).permit(:text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.sort_by { |u| -u.points }
    @count = Story.select(:user_id).distinct.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/guesses/new.html.erb
<h1>Guesses#new</h1>
<p>Find me in app/views/guesses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<% if user_signed_in? %>
		<%= link_to 'Current Ranking', controller: 'users' %> | 
		<%= link_to 'Read and Guess', controller: 'stories' %> | 
		<%= link_to 'Share a Story', new_story_path %> | 
	  	<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with model: @story, local: true do |form| %>
 
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@story.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @story.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.text_area :text, size: "20x7", maxlength: 140 %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<center><h1>Plat4Life 2018 Game</h1></center>

<p>Socialize with your colleagues and try to find out who these stories belong to.
<br/>
You only get one shot at each!</p>
 
<h3>Pending Stories</h3>
<table>
  <% @other_user_stories.each do |story| %>
    <tr>
	  <% if !story.user_has_guessed?(current_user) %>
	  	<td align="left"><%= story.text %></td>
	  	<td align="right"><%= link_to 'Guess', story_path(story) %></td>
	  <% end %>
    </tr>
  <% end %>
</table>

<h3>My Shared Stories</h3>
<table>
  <% @current_user_stories.each do |story| %>
    <tr>
	  <td align="right"><%= link_to 'Edit', edit_story_path(story) %></td>
      <td align="left"><%= story.text %></td>
    </tr>
  <% end %>
</table>

<h3>My Guesses</h3>
<table>
  <tr>
    <th>Story</th>
	<th>My Guess</th>
  </tr>
  <% @guessed_stories.each do |story| %>
    <tr>
		<td align="left"><%= story.text %></td>
	  	<td align="right"><%= story.get_guess_for_user(current_user).author.name %></td>
    </tr>
  <% end %>
</table>

app/views/stories/new.html.erb
<h2>New Personal Story</h2>

<% if @scount >= 20 && @gcount < 3 * @scount %>
You added over 20 stories, but have not made enough guesses. <br/>
Your number of guesses must be triple the number of stories to continue sharing.
<% else %>    

<%= form_with model: @story, local: true do |form| %>
 
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@story.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @story.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.text_area :text, size: "20x7" %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<p>
	Please read the story again before saving it.
	<br/>
	Make sure your writing is gender neutral.
	<br/>
	While possible, it is preferable not to modify the story once saved.
</p>
<% end %>
<% end %>

app/views/stories/show.html.erb
<h2>Who wrote this story?</h2>

<p><%= @story.text %></p>

<% if @story.user != current_user && !Guess.where(user: current_user, story: @story).exists?  %>
	<h3>My guess:</h3>
	<%= form_with(model: [ @story, @story.guesses.build ], local: true) do |form| %>
		 
	<%= form.select(:author_id) do %>	  
		<%= options_from_collection_for_select(User.where.not(id: current_user.id), :id, :name) %>
	<% end %>
		  
	<p><%= form.submit %></p>
	<% end %>
<% end %>

app/views/users/index.html.erb
<center><h1>Plat4Life 2018 Game</h1></center>
<center><h2>Current Ranking</h2></center>

<style>
	th, td { padding-right: 15px; }
</style>

<center>
  	<% if @count < 10 %>
    	Only <%= @count %> people have shared stories. At least 10 are needed before ranking is displayed.
  	<% else %>
		<table>
			<tr>
				<th> </th>
				<th>Stories</th>
				<th>Guesses</th>
				<th>Interest</th>
				<th>Correct</th>
				<th>Points</th>
			</tr>
  	  	   <% @users.each do |user| %>
			<tr>
				<td align="left"><%= user.name %></td>
				<td align="right"><%= user.number_of_stories %></td>
				<td align="right"><%= user.number_of_guesses %></td>
				<td align="right"><%= user.interest_in_stories %></td>
				<td align="right"><%= user.correct_guesses %></td>
				<td align="right"><%= user.points %></td>
			</tr>
			<% end %>
		<% end %>
	</table>
</center>

<br/>

<center>
<b>Points</b> = 2 x <b>Stories</b> + <b>Guesses</b> + <b>Interest</b> + 10 x <b>Correct</b>
</center>

<h3>Point system:</h3>
<ul>
	<li><b>2 pt</b> for sharing a personal story</li>
	<li><b>1 pt</b> for attempting to guess who wrote a story</li>
	<li><b>1 pt</b> for each attempted guess on your stories</li>
	<li><b>10 pt</b> for each correct guess</li>
</ul>